module.exports = [
  { name: "Kung Pao Chicken", category: "Stir-fry", spicy: true, description: "Classic spicy chicken", price: { student: 12, staff: 16, visitor: 22 } },
  { name: "Mapo Tofu", category: "Stir-fry", spicy: true, price: { student: 8, staff: 12, visitor: 18 } },
  { name: "Sweet and Sour Pork", category: "Stir-fry", price: { student: 14, staff: 18, visitor: 25 } },
  { name: "Braised Pork Belly", category: "Stir-fry", price: { student: 18, staff: 24, visitor: 32 } },
  { name: "Twice-Cooked Pork", category: "Stir-fry", spicy: true, price: { student: 15, staff: 20, visitor: 28 } },
  { name: "Egg Fried Rice", category: "Main", price: { student: 6, staff: 9, visitor: 14 } },
  { name: "Beef Fried Rice", category: "Main", price: { student: 10, staff: 14, visitor: 20 } },
  { name: "Yangzhou Fried Rice", category: "Main", price: { student: 12, staff: 16, visitor: 22 } },
  { name: "Beef Noodle Soup", category: "Noodles", price: { student: 12, staff: 16, visitor: 24 } },
  { name: "Dan Dan Noodles", category: "Noodles", spicy: true, price: { student: 9, staff: 13, visitor: 19 } },
  { name: "Chongqing Noodles", category: "Noodles", spicy: true, price: { student: 10, staff: 14, visitor: 20 } },
  { name: "Hot and Sour Rice Noodles", category: "Noodles", spicy: true, price: { student: 8, staff: 12, visitor: 18 } },
  { name: "Roujiamo (Meat Burger)", category: "Main", price: { student: 10, staff: 14, visitor: 20 } },
  { name: "Jianbing (Chinese Crepe)", category: "Main", price: { student: 7, staff: 10, visitor: 16 } },
  { name: "Tomato Egg Drop Soup", category: "Soup", price: { student: 5, staff: 8, visitor: 12 } },
  { name: "Hot and Sour Soup", category: "Soup", spicy: true, price: { student: 6, staff: 9, visitor: 14 } },
  { name: "Seaweed Egg Soup", category: "Soup", price: { student: 5, staff: 8, visitor: 12 } },
  { name: "Coca-Cola", category: "Drink", price: { student: 4, staff: 5, visitor: 7 } },
  { name: "Sprite", category: "Drink", price: { student: 4, staff: 5, visitor: 7 } },
  { name: "Iced Lemon Tea", category: "Drink", price: { student: 6, staff: 8, visitor: 12 } },
  { name: "Fresh Orange Juice", category: "Drink", price: { student: 10, staff: 14, visitor: 20 } },
  { name: "Soy Milk", category: "Drink", price: { student: 4, staff: 6, visitor: 10 } },
  { name: "Bubble Milk Tea", category: "Drink", price: { student: 10, staff: 13, visitor: 18 } },
  { name: "Dumplings (10pcs)", category: "Main", price: { student: 10, staff: 15, visitor: 22 } },
  { name: "Steamed Buns", category: "Main", price: { student: 3, staff: 5, visitor: 9 } }
];